# FROM authController
# REGISTER USER (WITH OUT ADDRESS)
###
POST http://localhost:8080/api/auth/register HTTP/1.1
Content-Type:application/json

{  
    "first_name": "test",
    "last_name": "test",
    "password":"123456"
}

# FROM usersController
# GET ALL USERS
###
GET http://localhost:8080/api/users/ HTTP/1.1

# GET USER BY ID
###
GET http://localhost:8080/api/users/2 HTTP/1.1


# DELETE USER BY ID
###
DELETE  http://localhost:8080/api/users/3 HTTP/1.1


# FROM customerController
# REGISTER USER (WITH OUT ADDRESS)
###
POST http://localhost:8080/api/customers/register HTTP/1.1
Content-Type:application/json

{  
    "company_name": "PI Trading",
    "first_name": "test",
    "last_name": "test",
    "password":"123456"
}